steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker build . \
          --build-arg=CODECOV_TOKEN=$$CODECOV_TOKEN \
          --build-arg=BRANCH_NAME=$BRANCH_NAME \
          --build-arg=COMMIT_SHA=$COMMIT_SHA \
          --build-arg=NPM_TOKEN=$$NPM_TOKEN \
    secretEnv:
      - CODECOV_TOKEN
      - NPM_TOKEN
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/CODECOV_TOKEN/versions/latest
      env: CODECOV_TOKEN
    - versionName: projects/$PROJECT_ID/secrets/NPM_TOKEN/versions/latest
      env: NPM_TOKEN
