steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - -c
      - |
          set -euo

          get-secret() {
            gcloud secrets versions access latest --secret="$1" --format='get(payload.data)' | tr '_-' '/+' | base64 -d
          }
          echo "//registry.npmjs.org/:_authToken=\"$( get-secret NPM_TOKEN )\"" >> .npmrc
  - name: gcr.io/cloud-builders/docker
    args: [ "build", "." ]
